### DISCUSSION TITLE
Simple two column document

### DISCUSSION THREAD

**Discussion by mbrannstrom** [Mogztter/asciidoctor-web-pdf#588] [Q&A]
Hi,

I tried to create a simple two-column document with multiple pages, but I cannot make it work (using 1.0.0-alpha.3). The text does not flow as I want, see attached files.

Input:
* [lorem-ipsum.adoc](https://github.com/Mogztter/asciidoctor-pdf.js/files/3819659/lorem-ipsum.adoc.txt)
* [twocolumn.css](https://github.com/Mogztter/asciidoctor-pdf.js/files/3819660/twocolumn.css.txt)

Output (which does not look that nice):
* [lorem-ipsum.pdf](https://github.com/Mogztter/asciidoctor-pdf.js/files/3819650/lorem-ipsum.pdf)

Is two-column mode possible? If so, how?

It would be nice with a two column document example or pre-made styles/templates (#43) with multiple levels of sections and long paragraphs. The cheat-sheet example is close, but not simple to generalize.

Regards,
Mikael Brännström

**Comment by ggrossetie** [comment]
Hi @mbrannstrom 

Something like this [sample.pdf](https://github.com/Mogztter/asciidoctor-pdf.js/files/3819791/sample.pdf)?

Here's the CSS:


```css
@page {
  size: A4; /* ; was missing */
  margin: 15mm 10mm 15mm 10mm;
}

div#content.content {
  /* removed margin */
  padding: 0;
  height: calc(100vh - 50mm);
  display: flex;
  flex-direction: column;
  flex-wrap: wrap;
}

.sect1, #preamble {
  column-count: 2; /* 2 columns */
  margin-right: 0.6cm;
  margin-left: 0.6cm;
  text-align-last: start; /* workaround a bug in Paged.js */
}

/* Some rules to make it look better */
h2 {
  margin-top: 0;
  break-before: always;
}

.sect1+.sect1 {
  border-top: none;
}

.sect2 {
  break-inside: avoid;
}
```

**Comment by ggrossetie** [comment]
Please keep in mind that the default stylesheet will be replaced by the custom stylesheet in the next version.

If you want to keep using the default stylesheet and override only a few rules, you will need to update the `stylesheet` attribute:

```
:stylesheet: asciidoctor-pdf/css/asciidoctor.css;asciidoctor-pdf/css/document.css;asciidoctor-pdf/css/features/title-document-numbering.css;twocolumn.css
```

Alternatively, you can copy-paste the content of `asciidoctor.css`, `document.css` and `title-document-numbering.css` to create your own stylesheet.

**Comment by mbrannstrom** [comment]
Yes, now it looks much better. Thanks!

Still some odd behavior, like the last page which has wrapped into two columns when it should fit into the first one.

**Comment by ggrossetie** [comment]
> Yes, now it looks much better. Thanks!

:+1: 

> Still some odd behavior, like the last page which has wrapped into two columns when it should fit into the first one.

Yes, I'm not sure what's the best way to solve this behavior.... as far as I know, `column-count` will distribute the content evenly (same height). You can probably avoid column break on paragraph:

```css
.paragraph {
  break-inside: avoid-column;
}
```

**Comment by ggrossetie** [comment]
> It would be nice with a two column document example or pre-made styles/templates (#43) with multiple levels of sections and long paragraphs. The cheat-sheet example is close, but not simple to generalize.

Feel free to add an example in `examples/document` :wink:

**Comment by jonathanhanna** [comment]
> > Still some odd behavior, like the last page which has wrapped into two columns when it should fit into the first one.
> 
> Yes, I'm not sure what's the best way to solve this behavior.... as far as I know, `column-count` will distribute the content evenly (same height).

The normal way to fix this issue is to use `column-fill: auto`. However, using this alone doesn't work with Chrome. According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/column-fill), you need to also add a `height` property. So far, this is working for me!

I'm still a bit confused regarding the best value to use for `height`. You'll run into problems if the value is too large or too small. The following worked for me (using 8.5 x 11in page layout with 0.5 in margins):
```css
#content {
    column-count: 2;
    column-gap: 0.25in;
    column-fill: auto;
    height: 10in;
}
```
My apologies for using imperial units :smile:.
