### DISCUSSION TITLE
Embed Custom TTF Font

### DISCUSSION THREAD

**Discussion by mariomuja** [Mogztter/asciidoctor-web-pdf#592] [Q&A]
Is it supported to embed a custom font from a TTF file into the generated PDF and how can I control this in the ADOC file or custom CSS?
Thanks, Mario

**Comment by ggrossetie** [comment]
Hello Mario,

You can take a look at https://github.com/Mogztter/asciidoctor-web-pdf/blob/master/tasks/update-font-face.js

It will generate something like:

```css
@font-face {
  font-family: 'Droid Sans Mono';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url(data:application/font-woff2;charset=utf-8;base64,d09GMgABA.....) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```


The idea is to encode the font in base64 and inline it in the CSS.
I believe that the font is then embed in the PDF when the PDF is generated from Chrome.
