### DISCUSSION TITLE
Minimal line thickness

### DISCUSSION THREAD

**Discussion by marcdus** [Mogztter/asciidoctor-web-pdf#690] [Q&A]
Hi, I am styling a template for technical documents, and want to use the standard scientific table form (thick line separates header and footer, hairlines in between rows). The minimal line thickness is rather high though. The thinnest lines I could achieve are:
![image](https://github.com/ggrossetie/asciidoctor-web-pdf/assets/95616936/c1b9d10d-bbea-4154-8ce8-9267c246b4c2)

Using this CSS:
```css
/* set width of bottom table separator line */
table.grid-all>tbody>tr:last-child>.tableblock, table.grid-all>thead:last-child>tr>.tableblock, table.grid-rows>tbody>tr:last-child>.tableblock, table.grid-rows>thead:last-child>tr>.tableblock {
    border-bottom-width: 2px;
}

/* set width of inner table separator line */
table.grid-rows>thead>tr>.tableblock, table.grid-rows>tbody>tr>.tableblock {
    border-width: 0 0 1px 0;
}*/
```

When checking the resulting PDF on different PDF readers, the thin lines usually appear thicker than the font and always have a fixed pixel width, unlike fonts that use anti-aliasing (or whatever using half-shaded pixel is called).

Is there way to bring down that minimal thickness? Other units like em, pt, etc. and decimal values have not worked for me. `thin` gives the same result as `1px` it seems like.
