### ISSUE TITLE
Use arabic numerals starting from "1" on the first section or chapter page

### ISSUE THREAD

**Issue by Mogztter** [Mogztter/asciidoctor-web-pdf#253]
> Core matter (the main body of the book) should be numbered with Arabic numerals (4, 11) starting from “1” on the first section or chapter page. Some publishers use Roman numerals for the front matter, and carry on the sequence in Arabic numbers (i, ii, iii, iv, v, 6, 7, 8 etc.), but this is not ideal. Roman numerals are used for the front matter of the book to allow additional pages to be added in the front matter without re-flowing the page numbers throughout the book. All pages, including blank pages, are included in the core matter numbering even if the page numbers are not visible on the page.

https://www.artbookbindery.com/guide/page-numbering

**Comment by danyill** [comment]
(Unfortunately the link above is now 404 waiting on website payment.)

To implement the above numbering scheme we need to be able to identify the first section or chapter page in our output. It is not easy after pagedjs processing or in Asciidoctor output as far as I can tell.

What is the first section or chapter? I thought it might be the first `sect1` element although that may be too simple.

`first-of-type` or `nth-child` or `first-of-class` all result in multiple hits within the html produced by asciidoctor-web-pdf. Partly I think this is caused by chunking.

I was trying to do something like: 

```css
.sect1:first-of-type(1) {
  counter-reset: page 1;
}
```
or


```css
.pagedjs_page.pagedjs_tableofcontents_page + div.pagedjs_page .sect1 {
 counter-reset: page 1;  
}
```

![image](https://user-images.githubusercontent.com/674783/120045735-ca67e080-c064-11eb-97b5-e5799c1bc3d1.png)

I really thought this might provide the next page after the table of contents with a heading. But alas. Something similar would work fine in Asciidoctor:

![image](https://user-images.githubusercontent.com/674783/120045326-d7d09b00-c063-11eb-8c3c-6072a78a9a19.png)

```css
.pagedjs_page.pagedjs_tableofcontents_page + div.pagedjs_page:first-of-type {
 counter-reset: page 1;  
}
```

This option doesn't work "Error: item doesn't belong to list" because I think `first-of-type` is a list thing.

My tentative conclusion is that standard css selectors are not working out and the root cause is that the first section/chapter should be more clearly identified in the html output:

* Should our converter identify the first section more clearly for styling purposes and (especially) to support improved page numbering? How would we do this - would we need a TreeProcessor to add this information?
* Would we want pagedjs to provide a an identifier for the page after the table of contents?
* One alternative is manipulating via js but that feels like a workaround and could cause complexity in the pagedjs interaction.
