### ISSUE TITLE
How to add complex footers?

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [Mogztter/asciidoctor-web-pdf#312]
Hey,

I am thinking about writing invoices using asciidoctor-web-pdf. For this, I need to set a complex multiline footer on my document.

I found this issue: #128 

And I am able to put some text into the footer like this:

```
@page {
    size: A4;
    @bottom-center {
        content: "Hello world";
    }
}
```

But how can I put more complex content into it? Issue #128 talks about the passthrough syntax:

```
++++
<table class="bottom-title-block">
  ...
</table>
++++
```

But I do not understand how I can put this into the footer.

**Comment by Mogztter** [comment]
Hello @RudolfVonKrugstein 

I think the important part is:

> It appears that if you declare the header content in CSS with `element()` instead of the counter method, and create the necessary named HTML in the body and add the `running` CSS attribute to it, it will be removed from the body and put in the header instead.

I didn't try but you will most likely need to declare something like:

```css
@page {
  margin: 1.5cm;
  size: A4;
  @bottom-center {
    content: element(bottom-title-block); 
  }
}
.bottom-title-block { 
   position: running(bottom-title-block); 
}
```

To use custom styles, please read the "Custom styles" second in https://github.com/Mogztter/asciidoctor-web-pdf#configuration

If you make it work, and since this feature can be useful in many cases, please feel free to contribute documentation, I will gladly review it :hugs:

**Comment by Mogztter** [comment]
I can confirm that this approach is working.
There was a few annoying issues but I took care of them. In the upcoming version, you will be able to provide running elements in a docinfo file. You can then position then position them in the bottom margin of the page (footer).

Here's an example (not yet released):

**report.adoc**
```
= 2021 Annual Report
:docinfo: private
```

**report-docinfo-running-pdf.html***
```html
<address class="contact-us">
  <strong>Handicap International</strong><br>
  138, avenue des Frères Lumière<br>
  69008 Lyon - France
</address>
```

**style.css**
```css
.contact-us {
  width: 6cm;
  position: running(runningContact)
}

@page {
  margin: 1cm 2cm 4cm 2cm;
}

@page :right {
  @bottom-left {
    content: element(runningContact)
  }

  @bottom-right {
    content: counter(page);
    margin: 10pt 10pt 30pt 0;
  }
}

@page :left {
  @bottom-right {
    content: element(runningContact)
  }

  @bottom-left {
    content: counter(page);
    margin: 10pt 0 30pt 10pt;
  }
}
```

```console
$ asciidoctor-web-pdf report.adoc -a stylesheet="+style.css"
```

![report](https://user-images.githubusercontent.com/333276/107795080-87555c00-6d58-11eb-87f1-861a78bf2b92.png)
