### ISSUE TITLE
Does not support certain CSS pseudo-classes and selectors (:nth() and :first)

### ISSUE THREAD

**Issue by blueray453** [Mogztter/asciidoctor-web-pdf#707]
The following code does not work.

```
@page clean {
    @bottom-right {
        content: none;
    }

    @bottom-left {
        content: none;
    }
}

@page :nth(1) {
    page: clean;
}

@page :first {
    page: clean;
}
```

Giving error.

```
An uncaught exception happened within the HTML page: Error: DOMException: Failed to execute 'querySelectorAll' on 'DocumentFragment': ':first' is not a valid selector.

An uncaught exception happened within the HTML page: Error: DOMException: Failed to execute 'querySelectorAll' on 'DocumentFragment': ':nth(1)' is not a valid selector.
```

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ggrossetie** [comment]
This should be fixed now that the Paged.js rendering engine has been replaced with Vivliostyle (#725, merged in `main`).

I retested with the exact CSS from this issue:

```css
@page clean {
    @bottom-right {
        content: none;
    }

    @bottom-left {
        content: none;
    }
}

@page :nth(1) {
    page: clean;
}

@page :first {
    page: clean;
}
```

The conversion now completes successfully with no exceptions — no more `DOMException: Failed to execute 'querySelectorAll' ... ':first' is not a valid selector`. The old error came from Paged.js doing its own DOM-based page-selector matching via `querySelectorAll`, which choked on these pseudo-classes; Vivliostyle handles page selectors natively and doesn't hit that code path.

Please reopen if you still see this with the latest release.
